# Generated by Django 2.2 on 2020-02-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='publish date'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='app.Genre'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='publish date'),
        ),
    ]
